### ISSUE TITLE
broken atom feed

### ISSUE THREAD

**Issue by ysm-dev** [jiyeonseo/jiyeonseo.github.io#1]
![image](https://user-images.githubusercontent.com/18487241/51087316-1fa53f00-1795-11e9-9f2f-269494ff04dd.png)

블로그 XML feed에 오류가 있어서 블로그 feed를 제대로 받지 못하고있습니다.

뭐가 문제인지는 몰라서 이슈로 남깁니다.

**Comment by jiyeonseo** [comment]
@ysm0622 엇!! 이슈 감사합니다!! 확인해볼께요 😃!!!
