### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by trustin** [jiyeonseo/jiyeonseo.github.io#8]
Would you mind adding an RSS feed to the generated web site so I can subscribe to your blog? :bow:

**Comment by jiyeonseo** [comment]
Thanks for the suggestion :) will add RSS feed!

**Comment by jiyeonseo** [comment]
Here it is!  https://jiyeonseo.github.io/rss.xml  ☺️ 
Thanks for reading my blog :)  will post more interesting things!

**Comment by trustin** [comment]
Awesome! Just subscribed 😉
